server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
#      routes:
#        - id: auth
#          uri: lb://auth-app
#          predicates:
#            - Path=/api/auth/**
#          filters:
#            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://uit:uit123uit@127.0.0.1:9100/eureka
    register-with-eureka: true
    fetch-registry: true