###push_server

server:
  port: 8130

spring:
  application:
    name: push-center-app

eureka:
  client:
    service-url:
      defaultZone: http://uit:uit123uit@127.0.0.1:9100/eureka
    register-with-eureka: true
    fetch-registry: true
push-server:
  user-online-state:
    endpoints:
      - web
      - ios
  multi-redis-source:
    online-state:
      host: localhost
      port: 6379
      password: redis_pass_pass
      database: 1
      jedis:
        pool:
          max-active: 8
    message-temporary-storage:
      host: localhost
      port: 6379
      password: redis_pass_pass
      database: 2
      jedis:
        pool:
          max-active: 8
